In [ ]:
#Task:Create a 3×5 matrix filled with numbers from
#1to15.Compute its transpose and printbo the original and transposed shapes.
import numpy as np
matrix=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
matrix_transpose=matrix.T
print(matrix.shape)
print(matrix_transpose.shape)


(3, 5)
(5, 3)


In [ ]:
# Task:Given a matrix X ofshape(4,3),compute its Grammatrix
# G=(X^T)(X) of shape(3,3) using matrix multiplication.
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
x_transpose=x.T
Multiplication=x_transpose@x
print(Multiplication)
print(Multiplication.shape)

[[166 188 210]
 [188 214 240]
 [210 240 270]]
(3, 3)


In [ ]:
# Convert a 1Darray‘v=np.array([2,4,6])‘ into
# a columnvector(3,1) and compute its matrix product with its row vector equivalent(1,3).
D1_array=np.array([2,3,6])
col_array=D1_array.T
multiply=D1_array@col_array
print(multiply)

49
