In [ ]:
#Task1:
#1.Create a 1D NumPy array with 15 random integers between $1$ and $100$.
#2.Extract all odd numbers that are strictly greater than $30$.
#3.Replace every number in the original array that is divisible by $5$ with $-1$.
import numpy as np
array=np.array([1,5,67,77,34,3,23,22,11,22,35,87,89,78,88])

mask=(array%2 != 0) & (array>30)
print(array[mask])

array[array%5==0]=-1
print(array)


[67 77 35 87 89]
[ 1 -1 67 77 34  3 23 22 11 22 -1 87 89 78 88]


In [66]:
#Task2:
#1.Given arr = np.array([10, 20, 30, 40, 50, 60, 70, 80]), extract elements at indices 1, 3, 3, and 6 in a single line.
#2.Reorder arr in reverse order using an integer index array (without using [::-1]).

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
extraction=arr[[1,3,3,6]]
print(extraction)
reverse=np.arange(len(arr)-1,-1,-1)
print(reverse)


[20 40 40 70]
[7 6 5 4 3 2 1 0]
