In [44]:
#Kaggle:
# Exercise 1. Import numpy as np and see the version

import numpy as np
print(np.__version__)

2.5.3


In [45]:
# Exercise 2. How to create a 1D array?
array=np.array([1,2,3,4,5]) #or
array21=np.arange(20)
array22=np.linspace(0,100,5)
print(array,"",array21,"",array22)

[1 2 3 4 5]  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]  [  0.  25.  50.  75. 100.]


In [46]:
#  Exercise 3. How to create a boolean array?
# array31=np.arange(20),dtype=bool
# boolean_array31=array31
# print((boolean_array31.dtype))

In [47]:
#Exercise 4. How to extract items that satisfy a given condition from 1D array?
#Question : Extract all odd numbers from array
array41=np.arange(25)
mask41=(array41%2)!=0
print(array41[mask41])

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [48]:
#Exercise 5. How to replace items that satisfy a condition with another value in numpy array?
## Question: Replace all odd numbers in arr with -1
array51=(np.random.random(50)*100).astype(int)
print(f"Orignal array:{array51}")
array51[array51%2!=0]=-1
print(array51)

Orignal array:[25 18 57 96 11 77  3 61 40 81  8 58  5 59 40 17 72 41 48 45 87 11 33  9
  5 71 17 96 61 79 68 64 69 65 13 15 47 31 89 97 28 91 15  1 49  6 65 66
 44 67]
[-1 18 -1 96 -1 -1 -1 -1 40 -1  8 58 -1 -1 40 -1 72 -1 48 -1 -1 -1 -1 -1
 -1 -1 -1 96 -1 -1 68 64 -1 -1 -1 -1 -1 -1 -1 -1 28 -1 -1 -1 -1  6 -1 66
 44 -1]


In [49]:
#Exercise 6. How to replace items that satisfy a condition without affecting the original array?
# Question: Replace all odd numbers in arr with -1 without changing arr
array61=np.arange(40)
Copy_array61=array61.copy()
Copy_array61[Copy_array61%2!=0]=-1
print(array61)
print(Copy_array61)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1
 24 -1 26 -1 28 -1 30 -1 32 -1 34 -1 36 -1 38 -1]


In [50]:
#Exercise 7. How to reshape an array?
# Question: Convert a 1D array to a 2D array with 2 rows
array71=np.array([23,45,67,55,888,66])

print(array71.reshape(2,3))

[[ 23  45  67]
 [ 55 888  66]]


In [55]:
#Exercise 8. How to stack two arrays vertically?
#Question: Stack arrays a and b vertically
array81=np.array([12,24,36,48,60])
array82=np.array([10,20,30,40,50])
new_array8=np.vstack([array81,array82])

print(new_array8.reshape(5,2))


[[12 24]
 [36 48]
 [60 10]
 [20 30]
 [40 50]]


In [56]:
# Exercise 9. How to stack two arrays horizontally?
# Question: Stack the arrays a and b horizontally.
array91=np.array([12,43,56,78,65])
array92=np.array([2,4,6,8,10])
print(np.stack([array91,array92]))


[[12 43 56 78 65]
 [ 2  4  6  8 10]]


In [58]:
# Exercise 10. How to generate custom sequences in numpy without hardcoding?
# Question: Create the following pattern without hardcoding. Use only numpy functions 
# and the below input array.
array101=np.array([23,34,32,33,45]*23)
print(array101)


[23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33
 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32
 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34
 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23
 34 32 33 45 23 34 32 33 45 23 34 32 33 45 23 34 32 33 45]
