In [ ]:
# Given a 3×3 matrix M, subtract the row-wise maximum from each row
import numpy as np
arr_1=np.array([[23,45,65],
                [34,55,66],
                [48,9,109]])
sem=np.max(arr_1,axis=0,keepdims=True)
print(arr_1)

[[ 23  45  65]
 [ 34  55  66]
 [ 48   9 109]]
