In [5]:
import numpy as np
arr_1=np.array([49,36,45])
arr_2=np.array([4,55,66])
print(arr_1+arr_2)
#Now we try multiply matrices
print(arr_1*arr_2) #or
multi=np.add(arr_1,arr_2)
print(multi)

[ 53  91 111]
[ 196 1980 2970]
[ 53  91 111]
